2022-03-14 15:19:31,126 INFO    BackendThr:15432 [internal.py:wandb_internal():90] W&B internal server running at pid: 15432, started at: 2022-03-14 15:19:31.125504
2022-03-14 15:19:31,126 INFO    MainThread:15432 [wandb_init.py:init():469] backend started and connected
2022-03-14 15:19:31,127 DEBUG   MainThread:15432 [config_util.py:dict_from_config_file():102] no default config file found in config-defaults.yaml
2022-03-14 15:19:31,129 INFO    MainThread:15432 [wandb_init.py:init():533] updated telemetry
2022-03-14 15:19:31,131 INFO    WriterThread:15432 [datastore.py:open_for_write():77] open: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\run-ac8gy287.wandb
2022-03-14 15:19:31,133 DEBUG   SenderThread:15432 [sender.py:send():234] send: header
2022-03-14 15:19:31,179 INFO    MainThread:15432 [wandb_init.py:init():563] communicating current version
2022-03-14 15:19:31,180 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: check_version
2022-03-14 15:19:31,181 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: check_version
2022-03-14 15:19:31,618 INFO    MainThread:15432 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-14 15:19:31,620 INFO    MainThread:15432 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-14 15:19:31,621 DEBUG   SenderThread:15432 [sender.py:send():234] send: run
2022-03-14 15:19:32,197 INFO    MainThread:15432 [wandb_init.py:init():606] starting run threads in backend
2022-03-14 15:19:32,198 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: run_start
2022-03-14 15:19:32,200 INFO    SenderThread:15432 [dir_watcher.py:__init__():169] watching files in: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files
2022-03-14 15:19:32,200 INFO    SenderThread:15432 [sender.py:_start_run_threads():807] run started: ac8gy287 with start time 1647251371
2022-03-14 15:19:32,201 DEBUG   SenderThread:15432 [sender.py:send():234] send: summary
2022-03-14 15:19:32,201 INFO    SenderThread:15432 [sender.py:_save_file():939] saving file wandb-summary.json with policy end
2022-03-14 15:19:32,213 DEBUG   HandlerThread:15432 [meta.py:__init__():40] meta init
2022-03-14 15:19:32,213 DEBUG   HandlerThread:15432 [meta.py:__init__():54] meta init done
2022-03-14 15:19:32,213 DEBUG   HandlerThread:15432 [meta.py:probe():214] probe
2022-03-14 15:19:32,229 DEBUG   HandlerThread:15432 [meta.py:_setup_git():204] setup git
2022-03-14 15:19:32,327 DEBUG   HandlerThread:15432 [meta.py:_setup_git():211] setup git done
2022-03-14 15:19:32,327 DEBUG   HandlerThread:15432 [meta.py:_save_pip():58] save pip
2022-03-14 15:19:32,327 DEBUG   HandlerThread:15432 [meta.py:_save_pip():72] save pip done
2022-03-14 15:19:32,327 DEBUG   HandlerThread:15432 [meta.py:_save_conda():79] save conda
2022-03-14 15:19:33,216 INFO    Thread-17 :15432 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\conda-environment.yaml
2022-03-14 15:19:33,216 INFO    Thread-17 :15432 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\wandb-summary.json
2022-03-14 15:19:33,217 INFO    Thread-17 :15432 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\requirements.txt
2022-03-14 15:19:34,467 DEBUG   HandlerThread:15432 [meta.py:_save_conda():89] save conda done
2022-03-14 15:19:34,468 DEBUG   HandlerThread:15432 [meta.py:probe():252] probe done
2022-03-14 15:19:34,474 DEBUG   SenderThread:15432 [sender.py:send():234] send: files
2022-03-14 15:19:34,474 INFO    SenderThread:15432 [sender.py:_save_file():939] saving file wandb-metadata.json with policy now
2022-03-14 15:19:34,496 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:19:34,496 INFO    MainThread:15432 [wandb_run.py:_console_start():1810] atexit reg
2022-03-14 15:19:34,496 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:19:34,513 INFO    MainThread:15432 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-03-14 15:19:34,514 INFO    MainThread:15432 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-03-14 15:19:34,516 INFO    MainThread:15432 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-14 15:19:34,516 INFO    MainThread:15432 [wandb_init.py:init():633] run started, returning control to user process
2022-03-14 15:19:35,227 INFO    Thread-17 :15432 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\conda-environment.yaml
2022-03-14 15:19:35,227 INFO    Thread-17 :15432 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\output.log
2022-03-14 15:19:35,228 INFO    Thread-17 :15432 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\wandb-metadata.json
2022-03-14 15:19:35,814 INFO    Thread-22 :15432 [upload_job.py:push():137] Uploaded file C:\Users\Welcome\AppData\Local\Temp\tmp_19m2qq5wandb\jcnpzubq-wandb-metadata.json
2022-03-14 15:19:37,240 INFO    Thread-17 :15432 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\output.log
2022-03-14 15:19:39,252 INFO    Thread-17 :15432 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\output.log
2022-03-14 15:19:49,985 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:19:49,986 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:20:03,617 DEBUG   SenderThread:15432 [sender.py:send():234] send: stats
2022-03-14 15:20:05,430 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:20:05,430 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:20:20,912 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:20:20,913 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:20:40,925 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:20:44,983 DEBUG   SenderThread:15432 [sender.py:send():234] send: stats
2022-03-14 15:20:44,983 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:21:00,338 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:21:00,338 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:21:01,275 WARNING FileStreamThread:15432 [file_stream.py:request_with_retry():599] requests_with_retry encountered retryable exception: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None)). func: <bound method Session.post of <requests.sessions.Session object at 0x00000178A30F5088>>, args: ('https://api.wandb.ai/files/ectc/translation_test/ac8gy287/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-03-14 15:21:09,870 DEBUG   SenderThread:15432 [sender.py:send():234] send: stats
2022-03-14 15:21:15,700 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:21:15,700 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:21:31,085 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:21:31,085 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:21:42,614 DEBUG   SenderThread:15432 [sender.py:send():234] send: stats
2022-03-14 15:21:46,461 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:21:46,461 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:22:01,828 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:22:01,828 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:22:15,401 DEBUG   SenderThread:15432 [sender.py:send():234] send: stats
2022-03-14 15:22:17,198 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:22:17,198 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:22:32,561 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:22:32,561 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:22:47,931 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:22:47,931 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:22:48,271 DEBUG   SenderThread:15432 [sender.py:send():234] send: stats
2022-03-14 15:23:03,280 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:23:03,280 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:23:18,651 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:23:18,652 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:23:21,300 DEBUG   SenderThread:15432 [sender.py:send():234] send: stats
2022-03-14 15:23:34,053 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:23:34,054 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:23:49,439 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:23:49,440 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:23:54,773 DEBUG   SenderThread:15432 [sender.py:send():234] send: stats
2022-03-14 15:24:04,837 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:24:04,837 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:24:20,299 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:24:20,300 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:24:28,125 DEBUG   SenderThread:15432 [sender.py:send():234] send: stats
2022-03-14 15:24:35,649 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:24:35,650 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:24:51,037 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:24:51,037 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:25:01,420 DEBUG   SenderThread:15432 [sender.py:send():234] send: stats
2022-03-14 15:25:06,396 DEBUG   HandlerThread:15432 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 15:25:06,397 DEBUG   SenderThread:15432 [sender.py:send_request():248] send_request: stop_status
2022-03-14 15:25:09,735 WARNING MsgRouterThr:15432 [router.py:message_loop():73] EOFError seen in message_loop
2022-03-14 15:25:09,887 INFO    MainThread:15432 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-03-14 15:25:09,888 INFO    MainThread:15432 [wandb_run.py:_restore():1752] restore
2022-03-14 15:25:10,495 INFO    SenderThread:15432 [sender.py:finish():1070] shutting down sender
2022-03-14 15:25:10,495 INFO    SenderThread:15432 [dir_watcher.py:finish():283] shutting down directory watcher
2022-03-14 15:25:10,511 INFO    WriterThread:15432 [datastore.py:close():281] close: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\run-ac8gy287.wandb
2022-03-14 15:25:11,324 INFO    SenderThread:15432 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\output.log
2022-03-14 15:25:11,324 INFO    SenderThread:15432 [dir_watcher.py:finish():313] scan: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files
2022-03-14 15:25:11,325 INFO    SenderThread:15432 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\conda-environment.yaml conda-environment.yaml
2022-03-14 15:25:11,325 INFO    SenderThread:15432 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\config.yaml config.yaml
2022-03-14 15:25:11,329 INFO    SenderThread:15432 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\output.log output.log
2022-03-14 15:25:11,330 INFO    SenderThread:15432 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\requirements.txt requirements.txt
2022-03-14 15:25:11,333 INFO    SenderThread:15432 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\wandb-metadata.json wandb-metadata.json
2022-03-14 15:25:11,336 INFO    SenderThread:15432 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\wandb-summary.json wandb-summary.json
2022-03-14 15:25:11,341 INFO    SenderThread:15432 [file_pusher.py:finish():177] shutting down file pusher
2022-03-14 15:25:11,342 INFO    SenderThread:15432 [file_pusher.py:join():182] waiting for file pusher
2022-03-14 15:25:12,340 INFO    Thread-34 :15432 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\wandb-summary.json
2022-03-14 15:25:12,419 INFO    Thread-33 :15432 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\requirements.txt
2022-03-14 15:25:12,423 INFO    Thread-30 :15432 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\conda-environment.yaml
2022-03-14 15:25:12,475 INFO    Thread-31 :15432 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\config.yaml
2022-03-14 15:25:12,477 INFO    Thread-32 :15432 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151931-ac8gy287\files\output.log
2022-03-14 15:25:13,194 ERROR   BackendThr:15432 [internal.py:wandb_internal():158] Thread HandlerThread:
Traceback (most recent call last):
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 302, in _recv_bytes
    overlapped=True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\context_enhancement\lib\site-packages\wandb\sdk\internal\internal_util.py", line 52, in run
    self._run()
  File "D:\Anaconda\envs\context_enhancement\lib\site-packages\wandb\sdk\internal\internal_util.py", line 99, in _run
    record = self._input_record_q.get(timeout=1)
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\queues.py", line 108, in get
    res = self._recv_bytes()
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
