2022-03-14 15:14:29,658 INFO    MainThread:18956 [wandb_setup.py:_flush():71] setting env: {'start_method': 'thread'}
2022-03-14 15:14:29,659 INFO    MainThread:18956 [wandb_setup.py:_flush():71] setting login settings: {}
2022-03-14 15:14:29,659 INFO    MainThread:18956 [wandb_init.py:_log_setup():371] Logging user logs to D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151429-1fuhi2pp\logs\debug.log
2022-03-14 15:14:29,659 INFO    MainThread:18956 [wandb_init.py:_log_setup():372] Logging internal logs to D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151429-1fuhi2pp\logs\debug-internal.log
2022-03-14 15:14:29,659 INFO    MainThread:18956 [wandb_init.py:init():404] calling init triggers
2022-03-14 15:14:29,660 INFO    MainThread:18956 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {'workers': 20, 'epochs': 2, 'batch_size': 64, 'learning_rate': 0.2, 'dropout': 0.01, 'weight_decay': 1e-06, 'clip': 1, 'betas': (0.9, 0.98), 'eps': 1e-09, 'loss_fn': 'cross_entropy', 'dmodel': 768, 'nhead': 3, 'dfeedforward': 256, 'nlayers': 3, 'tokenizer': 'bert-base-multilingual-cased', 'mbert_out_size': 768, 'checkpoint_dir': WindowsPath('checkpoint'), 'ngpus_per_node': 1, 'rank': 0, 'dist_url': 'tcp://localhost:58472', 'world_size': 1}
2022-03-14 15:14:29,660 INFO    MainThread:18956 [wandb_init.py:init():460] starting backend
2022-03-14 15:14:29,664 INFO    MainThread:18956 [backend.py:ensure_launched():216] starting backend process...
2022-03-14 15:14:29,665 INFO    MainThread:18956 [backend.py:ensure_launched():222] started backend process with pid: 0
2022-03-14 15:14:29,665 INFO    BackendThr:18956 [internal.py:wandb_internal():90] W&B internal server running at pid: 18956, started at: 2022-03-14 15:14:29.664469
2022-03-14 15:14:29,666 INFO    MainThread:18956 [wandb_init.py:init():469] backend started and connected
2022-03-14 15:14:29,668 INFO    MainThread:18956 [wandb_init.py:init():533] updated telemetry
2022-03-14 15:14:29,670 INFO    WriterThread:18956 [datastore.py:open_for_write():77] open: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151429-1fuhi2pp\run-1fuhi2pp.wandb
2022-03-14 15:14:29,722 INFO    MainThread:18956 [wandb_init.py:init():563] communicating current version
2022-03-14 15:14:29,871 INFO    MainThread:18956 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-14 15:14:29,874 INFO    MainThread:18956 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-14 15:14:30,349 INFO    MainThread:18956 [wandb_init.py:init():606] starting run threads in backend
2022-03-14 15:14:30,350 INFO    SenderThread:18956 [dir_watcher.py:__init__():169] watching files in: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151429-1fuhi2pp\files
2022-03-14 15:14:30,351 INFO    SenderThread:18956 [sender.py:_start_run_threads():807] run started: 1fuhi2pp with start time 1647251069
2022-03-14 15:14:30,353 INFO    SenderThread:18956 [sender.py:_save_file():939] saving file wandb-summary.json with policy end
2022-03-14 15:14:31,363 INFO    Thread-17 :18956 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151429-1fuhi2pp\files\conda-environment.yaml
2022-03-14 15:14:31,364 INFO    Thread-17 :18956 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151429-1fuhi2pp\files\requirements.txt
2022-03-14 15:14:31,364 INFO    Thread-17 :18956 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151429-1fuhi2pp\files\wandb-summary.json
2022-03-14 15:14:32,636 INFO    SenderThread:18956 [sender.py:_save_file():939] saving file wandb-metadata.json with policy now
2022-03-14 15:14:32,652 INFO    MainThread:18956 [wandb_run.py:_console_start():1810] atexit reg
2022-03-14 15:14:32,661 INFO    MainThread:18956 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-03-14 15:14:32,662 INFO    MainThread:18956 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-03-14 15:14:32,663 INFO    MainThread:18956 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-14 15:14:32,663 INFO    MainThread:18956 [wandb_init.py:init():633] run started, returning control to user process
2022-03-14 15:14:33,371 INFO    Thread-17 :18956 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151429-1fuhi2pp\files\conda-environment.yaml
2022-03-14 15:14:33,371 INFO    Thread-17 :18956 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151429-1fuhi2pp\files\output.log
2022-03-14 15:14:33,372 INFO    Thread-17 :18956 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151429-1fuhi2pp\files\wandb-metadata.json
2022-03-14 15:14:33,827 INFO    Thread-23 :18956 [upload_job.py:push():137] Uploaded file C:\Users\Welcome\AppData\Local\Temp\tmp3gsnc_tnwandb\268jdstf-wandb-metadata.json
2022-03-14 15:14:35,382 INFO    Thread-17 :18956 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151429-1fuhi2pp\files\output.log
2022-03-14 15:14:37,389 INFO    Thread-17 :18956 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151429-1fuhi2pp\files\output.log
2022-03-14 15:18:59,624 WARNING MsgRouterThr:18956 [router.py:message_loop():73] EOFError seen in message_loop
2022-03-14 15:18:59,752 INFO    MainThread:18956 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-03-14 15:18:59,754 INFO    MainThread:18956 [wandb_run.py:_restore():1752] restore
2022-03-14 15:19:00,087 INFO    WriterThread:18956 [datastore.py:close():281] close: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_151429-1fuhi2pp\run-1fuhi2pp.wandb
