2022-03-14 14:56:54,523 INFO    BackendThr:16796 [internal.py:wandb_internal():90] W&B internal server running at pid: 16796, started at: 2022-03-14 14:56:54.522049
2022-03-14 14:56:54,523 INFO    MainThread:16796 [wandb_init.py:init():469] backend started and connected
2022-03-14 14:56:54,524 DEBUG   MainThread:16796 [config_util.py:dict_from_config_file():102] no default config file found in config-defaults.yaml
2022-03-14 14:56:54,526 INFO    MainThread:16796 [wandb_init.py:init():533] updated telemetry
2022-03-14 14:56:54,527 INFO    WriterThread:16796 [datastore.py:open_for_write():77] open: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\run-3lre7lk3.wandb
2022-03-14 14:56:54,528 DEBUG   SenderThread:16796 [sender.py:send():234] send: header
2022-03-14 14:56:54,572 INFO    MainThread:16796 [wandb_init.py:init():563] communicating current version
2022-03-14 14:56:54,573 DEBUG   HandlerThread:16796 [handler.py:handle_request():130] handle_request: check_version
2022-03-14 14:56:54,573 DEBUG   SenderThread:16796 [sender.py:send_request():248] send_request: check_version
2022-03-14 14:56:54,764 INFO    MainThread:16796 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-14 14:56:54,766 INFO    MainThread:16796 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-03-14 14:56:54,767 DEBUG   SenderThread:16796 [sender.py:send():234] send: run
2022-03-14 14:56:55,295 INFO    MainThread:16796 [wandb_init.py:init():606] starting run threads in backend
2022-03-14 14:56:55,295 INFO    SenderThread:16796 [dir_watcher.py:__init__():169] watching files in: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files
2022-03-14 14:56:55,296 INFO    SenderThread:16796 [sender.py:_start_run_threads():807] run started: 3lre7lk3 with start time 1647250014
2022-03-14 14:56:55,296 DEBUG   SenderThread:16796 [sender.py:send():234] send: summary
2022-03-14 14:56:55,297 DEBUG   HandlerThread:16796 [handler.py:handle_request():130] handle_request: run_start
2022-03-14 14:56:55,298 INFO    SenderThread:16796 [sender.py:_save_file():939] saving file wandb-summary.json with policy end
2022-03-14 14:56:55,312 DEBUG   HandlerThread:16796 [meta.py:__init__():40] meta init
2022-03-14 14:56:55,312 DEBUG   HandlerThread:16796 [meta.py:__init__():54] meta init done
2022-03-14 14:56:55,312 DEBUG   HandlerThread:16796 [meta.py:probe():214] probe
2022-03-14 14:56:55,320 DEBUG   HandlerThread:16796 [meta.py:_setup_git():204] setup git
2022-03-14 14:56:55,417 DEBUG   HandlerThread:16796 [meta.py:_setup_git():211] setup git done
2022-03-14 14:56:55,417 DEBUG   HandlerThread:16796 [meta.py:_save_pip():58] save pip
2022-03-14 14:56:55,418 DEBUG   HandlerThread:16796 [meta.py:_save_pip():72] save pip done
2022-03-14 14:56:55,418 DEBUG   HandlerThread:16796 [meta.py:_save_conda():79] save conda
2022-03-14 14:56:56,312 INFO    Thread-17 :16796 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\conda-environment.yaml
2022-03-14 14:56:56,313 INFO    Thread-17 :16796 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\wandb-summary.json
2022-03-14 14:56:56,313 INFO    Thread-17 :16796 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\requirements.txt
2022-03-14 14:56:57,542 DEBUG   HandlerThread:16796 [meta.py:_save_conda():89] save conda done
2022-03-14 14:56:57,542 DEBUG   HandlerThread:16796 [meta.py:probe():252] probe done
2022-03-14 14:56:57,547 DEBUG   SenderThread:16796 [sender.py:send():234] send: files
2022-03-14 14:56:57,547 INFO    SenderThread:16796 [sender.py:_save_file():939] saving file wandb-metadata.json with policy now
2022-03-14 14:56:57,565 DEBUG   HandlerThread:16796 [handler.py:handle_request():130] handle_request: stop_status
2022-03-14 14:56:57,565 INFO    MainThread:16796 [wandb_run.py:_console_start():1810] atexit reg
2022-03-14 14:56:57,566 DEBUG   SenderThread:16796 [sender.py:send_request():248] send_request: stop_status
2022-03-14 14:56:57,583 INFO    MainThread:16796 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-03-14 14:56:57,583 INFO    MainThread:16796 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-03-14 14:56:57,585 INFO    MainThread:16796 [wandb_run.py:_redirect():1745] Redirects installed.
2022-03-14 14:56:57,585 INFO    MainThread:16796 [wandb_init.py:init():633] run started, returning control to user process
2022-03-14 14:56:58,324 INFO    Thread-17 :16796 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\conda-environment.yaml
2022-03-14 14:56:58,324 INFO    Thread-17 :16796 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\wandb-metadata.json
2022-03-14 14:56:58,324 INFO    Thread-17 :16796 [dir_watcher.py:_on_file_created():217] file/dir created: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\output.log
2022-03-14 14:56:59,399 INFO    Thread-22 :16796 [upload_job.py:push():137] Uploaded file C:\Users\Welcome\AppData\Local\Temp\tmpsyzxotu4wandb\1tw3pb3p-wandb-metadata.json
2022-03-14 14:57:00,342 INFO    Thread-17 :16796 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\output.log
2022-03-14 14:57:02,431 INFO    Thread-17 :16796 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\output.log
2022-03-14 14:57:02,496 INFO    MainThread:16796 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-03-14 14:57:02,497 WARNING MsgRouterThr:16796 [router.py:message_loop():73] EOFError seen in message_loop
2022-03-14 14:57:02,497 INFO    MainThread:16796 [wandb_run.py:_restore():1752] restore
2022-03-14 14:57:02,621 INFO    WriterThread:16796 [datastore.py:close():281] close: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\run-3lre7lk3.wandb
2022-03-14 14:57:02,621 INFO    SenderThread:16796 [sender.py:finish():1070] shutting down sender
2022-03-14 14:57:02,621 INFO    SenderThread:16796 [dir_watcher.py:finish():283] shutting down directory watcher
2022-03-14 14:57:03,445 INFO    SenderThread:16796 [dir_watcher.py:_on_file_modified():230] file/dir modified: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\output.log
2022-03-14 14:57:03,446 INFO    SenderThread:16796 [dir_watcher.py:finish():313] scan: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files
2022-03-14 14:57:03,446 INFO    SenderThread:16796 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\conda-environment.yaml conda-environment.yaml
2022-03-14 14:57:03,446 INFO    SenderThread:16796 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\config.yaml config.yaml
2022-03-14 14:57:03,447 INFO    SenderThread:16796 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\output.log output.log
2022-03-14 14:57:03,456 INFO    SenderThread:16796 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\requirements.txt requirements.txt
2022-03-14 14:57:03,458 INFO    SenderThread:16796 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\wandb-metadata.json wandb-metadata.json
2022-03-14 14:57:03,525 INFO    SenderThread:16796 [dir_watcher.py:finish():327] scan save: D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\wandb-summary.json wandb-summary.json
2022-03-14 14:57:03,527 INFO    SenderThread:16796 [file_pusher.py:finish():177] shutting down file pusher
2022-03-14 14:57:03,532 INFO    SenderThread:16796 [file_pusher.py:join():182] waiting for file pusher
2022-03-14 14:57:04,564 INFO    Thread-29 :16796 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\conda-environment.yaml
2022-03-14 14:57:04,585 INFO    Thread-30 :16796 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\config.yaml
2022-03-14 14:57:04,646 INFO    Thread-33 :16796 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\wandb-summary.json
2022-03-14 14:57:04,652 INFO    Thread-31 :16796 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\output.log
2022-03-14 14:57:04,655 INFO    Thread-32 :16796 [upload_job.py:push():137] Uploaded file D:\context_enhancement\context-main\combined\context_enhancement\wandb\run-20220314_145654-3lre7lk3\files\requirements.txt
2022-03-14 14:57:05,366 ERROR   BackendThr:16796 [internal.py:wandb_internal():158] Thread HandlerThread:
Traceback (most recent call last):
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 302, in _recv_bytes
    overlapped=True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\context_enhancement\lib\site-packages\wandb\sdk\internal\internal_util.py", line 52, in run
    self._run()
  File "D:\Anaconda\envs\context_enhancement\lib\site-packages\wandb\sdk\internal\internal_util.py", line 99, in _run
    record = self._input_record_q.get(timeout=1)
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\queues.py", line 108, in get
    res = self._recv_bytes()
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "D:\Anaconda\envs\context_enhancement\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
2022-03-14 14:57:08,193 INFO    MainThread:16796 [wandb_run.py:_wait_for_finish():1912] got exit ret: None
2022-03-14 14:57:08,300 INFO    MainThread:16796 [wandb_run.py:_restore():1752] restore
2022-03-14 14:57:08,329 INFO    MainThread:16796 [internal.py:handle_exit():77] Internal process exited
